version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./.redis:/data

  redis-init:
    image: goodsmileduck/redis-cli
    depends_on:
      - redis
    volumes:
      - ./scripts/init:/home/init
    # Create our index contained in /home/init/redis.txt
    entrypoint:
      [
        "sh",
        "-c",
        "cat /home/init/redis.txt | redis-cli -h redis --pipe"
      ]

  nextjs:
    profiles:
      - prod
    depends_on:
      # - prometheus
      - redis-init
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus:/etc/prometheus

  # e2e:
  #   profiles:
  #     - testing
  #   depends_on:
  #     - redis-init

  #   ports:
  #     - 3000:3000
  #   environment:
  #     - REDIS_HOST=redis
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   entrypoint: [ "yarn", "e2e:headless" ]
