version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./.redis:/data

  redis-init:
    image: goodsmileduck/redis-cli
    depends_on:
      - redis
    volumes:
      - ./scripts/init:/home/init
    # Create our index contained in /home/init/redis.txt
    # See https://redis.io/docs/interact/search-and-query/basic-constructs/configuration-parameters/ for config
    entrypoint:
      [
        "sh",
        "-c",
        "cat /home/init/redis.txt | redis-cli -h redis --pipe"
      ]

  nextjs:
    profiles:
      - prod
      - e2e
    depends_on:
      - redis-init
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "yarn", "next:start" ]

  cypress:
    profiles:
      - e2e
    depends_on:
      - redis-init
    image: cypress/included:3.2.0
    volumes:
      - ./:/e2e
    working_dir: /e2e
